fix form/input element ID
google/lium pull request #132
Opened 2023-10-30 09:01 UTC by wtrgjadmw

fix #119

2023-10-30 09:51 UTC, mhiramat approved these changes
LGTM

2023-10-31 01:58 UTC, hikalium requested changes

2023-10-31 01:58 UTC, hikalium commented on docs/servo_power_monitor/src/ui.ts
> +) as HTMLInputElement;
they should be lowerCamelCase, not UpperCamelCase
https://google.github.io/styleguide/tsguide.html#naming-rules-by-identifier-type

2023-10-31 02:33 UTC, wtrgjadmw commented
fixed to lowerCamelCase!

2023-10-31 02:36 UTC, hikalium approved these changes
Looks good! Thanks!!

2023-10-31 02:36 UTC, merged